export enum CALCULATOR_BUTTON_TYPES {
    CLEAR = 'clear',
    ROUND_BRACKETS = 'round-brackets',
    PERCENT = 'percent',
    DIVIDE = 'divide',
    MULTIPLY = 'multiply',
    SUBTRACT = 'subtract',
    ADD = 'add',
    EQUALS = 'equals',
    ZERO = 'zero',
    ONE = 'one',
    TWO = 'two',
    THREE = 'three',
    FOUR = 'four',
    FIVE = 'five',
    SIX = 'six',
    SEVEN = 'seven',
    EIGHT = 'eight',
    NINE = 'nine',
    DOT = 'dot'
}